### ISSUE TITLE
Pet types

### ISSUE THREAD

**Issue by asd86206** [EndlessCodeGroup/RPGInventory#122]
Can not get it

Zombie

Little zombie

When pets

```yaml
pets:
  zombie:
    name: "&D&lzombie"
    item-name: "&7&lzombie pet"
    lore:
    - "&e&Lzombie!"
    item: MONSTER_EGG:Ghast
    type: COMPANION
    health: 20
    damage: 1
    speed: 1
    attack-mobs: true
    attack-players: false
    revival: true
    cooldown: 60
    features:
    - "TYPE: "zombie"
```
