### ISSUE TITLE
Duplicating Horses, Armor, and Saddles/Chests.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#65]
Here is the error first and foremost.

https://pastebin.com/p9DAD3kb

For reference here are the two horses in the config:

```yaml
BlackHorse:
    name: "&6&lBlack Horse"
    item-name: "&5&lBlack Horse's Summoning Stone"
    lore:
    - "&e&oPitch Black Horse with a White colored theme."
    item: MONSTER_EGG:Zombie
    type: MOUNT
    health: 50
    speed: 6
    revival: true
    cooldown: 30
    features:
    - "CHEST: FALSE"
    - "ARMOR: DIAMOND_BARDING"
    - "COLOR: BLACK"
    - "STYLE: WHITEFIELD"
 ChestnutHorse:
    name: "&6&lChestnut Horse"
    item-name: "&5&lChestnut Horse's Summoning Stone"
    lore:
    - "&e&oChestnut Horse with a White colored theme."
    item: MONSTER_EGG:Zombie
    type: MOUNT
    health: 100
    speed: 100
    revival: true
    cooldown: 30
    features:
    - "CHEST: FALSE"
    - "ARMOR: DIAMOND_BARDING"
    - "COLOR: CHESTNUT"
    - "STYLE: WHITE_DOTS"
```

Then here is what happens:

The "Chestnut Horse" **_does NOT allow me to do the following error_**, only the "Black Horse". 

When I summon the "BlackHorse", the horse appears as described above. Black with Whitefield splashes. However, once I get on the BlackHorse: while I am mounted on the horse, I can press the E button, and see the inventory of the Horse, and proceed to un-equip the Diamond Horse Armor, along with the Saddle.

Once this is done, I can un-equip the Black Horse's Summoning Stone, then the horse stays summoned. Upon re-equipping the Summoning Stone again, another horse appears, with the armor and saddle on, allowing me to repeat the process infinitely. 

Here are pictures for reference:

https://imgur.com/a/c9EMf

Also, all duplicated horses are unable to be attacked/killed. I was able to drown and kill them to get rid of them however.
