### ISSUE TITLE
Item requirements in MythincMobs

### ISSUE THREAD

**Issue by trungbmt** [EndlessCodeGroup/RPGInventory#84]
I did not create items with rpginventory because it did not support drop mythicmobs, but when I created an item from mythicmobs there was lore
`"§6Level: lvl 50"`, when equipped in it still accept though my level is 40
When I checked, the item made from rpginventory had something else made from mythicmobs.
I want my stuff created from mythicmobs can still be used as rpginventory, it must request level like rpginventory, please help me ...
Sorry, my bad english

```yaml
ItemByRPGINVENTORY:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND_HOE
  damage: 25
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §6§7[§6§lEPIC§7]§e Agility Kornu Necklace
    lore:
    - '§6Level: lvl 50'
    - ''
    - §r--------------------------
    - '§aNhanh Nhẹn§r: +29'
    - '§aSát thương khi bắn§r: +14'
    - '§aTỉ lệ chí mạng§r: +10'
    - '§cMáu§r: +41'
    - §r--------------------------
    - ''
    - '§3Armor: §7+10%'
    ItemFlags: !!set
      HIDE_PLACED_ON: null
      HIDE_ENCHANTS: null
      HIDE_UNBREAKABLE: null
      HIDE_POTION_EFFECTS: null
      HIDE_ATTRIBUTES: null
      HIDE_DESTROYS: null
    Unbreakable: true
    internal: H4sIAAAAAAAAAONiYOBg4CwqSM/MK9PLTGEQS0zPzMksqdTNzi/KK9XNS03OzklMTmUAAIUkBYYoAAAA
```

```yaml
ItemByMythicmobs:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND_HOE
  damage: 25
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §6§7[§6§lEPIC§7]§e Agility Kornu Necklace
    lore:
    - '§6Level: lvl 50'
    - ''
    - §r--------------------------
    - '§aNhanh Nhẹn§r: +29'
    - '§aSát thương khi bắn§r: +14'
    - '§aTỉ lệ chí mạng§r: +10'
    - '§cMáu§r: +41'
    - §r--------------------------
    - ''
    - '§3Armor: §7+10%'
    Unbreakable: true
```
